name: Build and Deploy C# Website

on:
  push:
    branches:
      - main
    paths:
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      publish-path: ${{ steps.publish.outputs.publish-path }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        id: publish
        run: |
          dotnet publish \
            ./src/Site/Site.csproj \
            --configuration Release \
            --output ${{ github.workspace }}/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup SSH
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.SSH_HOST }}
        run: |
          # Start SSH agent
          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh

          # Add private key
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add host
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

      - name: To Windows server
        env:
          USERNAME: ${{ secrets.SSH_USER }}
          HOST: ${{ secrets.SSH_HOST }}
        run: |
          ssh "$USERNAME@$HOST" "powershell -Command Stop-WebSite -Name 'Site'"

          # ssh "$USERNAME@$HOST" "rm -rf 'C:/inetpub/wwwroot/Site/*'"

          scp -l 2000 -C \
            -o ServerAliveInterval=60 \
            -r ${{ github.workspace }}/publish/* \
            "$USERNAME@$HOST:'C:/inetpub/wwwroot/Site'"

          ssh "$USERNAME@$HOST" "powershell -Command Start-WebSite -Name 'Site'"
